apiVersion: skaffold/v2alpha1
kind: Config
build:
  artifacts:
  - image: bookmark-service
    docker:
      dockerfile: ./Dockerfile
  - image: bookmark-service-postgres
      docker:
        dockerfile: ./Dockerfile
  local:
    useDockerCLI: true
deploy:
  kubectl:
    manifests:
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    - k8s/api-service.yaml